apiVersion: v1
kind: Pod
metadata:
  name: "jpa-student09-pod03"
  labels:
    app: "jpa-student09-app"
spec:
  containers:
  - name: "jpa-student09-container03"
    image: "docker-registry.default.svc:5000/openshift/httpd:latest"
    ports:
    - containerPort: 8080
      protocol: TCP
