apiVersion: v1
kind: Pod
metadata:
  name: "jpa-student09-pod04"
  labels:
    app: "jpa-student09-app"
spec:
  containers:
  - name: "jpa-student09-container04"
    image: "docker-registry.default.svc:5000/openshift/httpd:latest"
    ports:
    - containerPort: 8080
      protocol: TCP
    volumeMounts:
      - name: "var-www"
        mountPath: "/var/www"
  volumes:
    - name: "var-www"
      persistentVolumeClaim:
        claimName: "jpa-student09-pvc-01"
